### ISSUE TITLE
could share the test video? I could not download it.

### ISSUE THREAD

**Issue by xinsuinizhuan** [spacewalk01/tensorrt-yolov6#1]
I also want to test

**Comment by spacewalk01** [comment]
I couldn't upload the test video directly to github because of its size. I will share the downloadable link here

**Comment by spacewalk01** [comment]
https://drive.google.com/file/d/1mjqQ4flnZgBj56tEgiK_Uc7zUDbdRbUx/view?usp=sharing

**Comment by xinsuinizhuan** [comment]
> https://drive.google.com/file/d/1mjqQ4flnZgBj56tEgiK_Uc7zUDbdRbUx/view?usp=sharing

could share with baidu pan? I have no google account

**Comment by xinsuinizhuan** [comment]
could share with baidu pan?

**Comment by spacewalk01** [comment]
Sorry, I don't have an account on baidu. I will try to upload the test video on other sharing platform. but you can use any video for test.

**Comment by spacewalk01** [comment]
there you go, it should work:
https://www.mediafire.com/file/kwxxa772ly4yy2t/test.mp4/file
